name: Deploy project

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  deploy-client:
    name: Deploy Client to Vercel
    if: github.repository == 'pet-tele/pet-game'
    
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel environment information
      working-directory: client
      run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

    - name: Install client dependencies
      working-directory: client
      run: npm ci

    - name: Build client
      working-directory: client
      run: npm run build

    - name: Deploy to Vercel
      run: vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}